server:
  port: 9001
  servlet:
    context-path: /gatway

spring:
  application:
    name: sca-gatway
  profiles:
    active:
    # 附件大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB