spring:
  cloud:
    gateway:
      globalcors:
        # 配置跨域
        cors-configurations:
          '[/**]':
            allow-credentials: true
            max-age: 1800
            allowed-headers:
            - "*"
            allowed-origins:
            - "*"
            allowed-methods:
            - "*"
      default-filters:
        # https://blog.51cto.com/u_1472521/4996298
        # https://blog.csdn.net/qq_37958845/article/details/119023786#:~:text=%E5%9C%A8Gateway%E4%B8%AD%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%20DedupeResponseHeader%20%E6%9D%A5%E5%A4%84%E7%90%86%E4%B8%80%E4%B8%8B%E5%93%8D%E5%BA%94%E5%A4%B4%E9%87%8D%E5%A4%8D%E7%9A%84%E9%97%AE%E9%A2%98%E3%80%82%20spring%3A%20cloud%3A%20gateway%3A%20default-filters%3A,-%20DedupeResponseHeader%3DVary%20Access-Control-Allow-Origin%20Access-Control-Allow%20-Credentials%2C%20RETAIN_FIRST%201
        # 解决跨域响应头重复属性问题：调用的下游服务也配置有跨域相关内容，导致响应头属性重复
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      discovery:
        locator:
          # 开启基于使用discovery client 注册中心注册的服务来创建路由
          enabled: true
